-- MySQL Script generated by MySQL Workbench
-- 05/10/15 19:05:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sticker_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sticker_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sticker_db` ;

-- -----------------------------------------------------
-- Table `sticker_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sticker_db`.`User` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sticker_db`.`Stick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sticker_db`.`Stick` (
  `stickId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userEmail` VARCHAR(45) NOT NULL,
  `albumId` INT NULL DEFAULT -1,
  `stickTitle` VARCHAR(45) NOT NULL DEFAULT 'unknown',
  `stickImage` VARCHAR(45) NULL,
  `stickTime` DATETIME NOT NULL,
  `stickLocation` VARCHAR(45) NOT NULL,
  `stickInfo` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`stickId`, `userEmail`),
  UNIQUE INDEX `stickId_UNIQUE` (`stickId` ASC),
  UNIQUE INDEX `userId_UNIQUE` (`userEmail` ASC),
  CONSTRAINT `userEmail`
    FOREIGN KEY (`userEmail`)
    REFERENCES `sticker_db`.`User` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sticker_db`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sticker_db`.`Album` (
  `albumId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userEmail` VARCHAR(45) NOT NULL,
  `albumTitle` VARCHAR(45) NOT NULL DEFAULT 'unknown',
  `albumInfo` VARCHAR(140) NULL,
  PRIMARY KEY (`albumId`, `userEmail`),
  UNIQUE INDEX `albumId_UNIQUE` (`albumId` ASC),
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC),
  CONSTRAINT `userEmail`
    FOREIGN KEY (`userEmail`)
    REFERENCES `sticker_db`.`User` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
